import type { GameState } from "./types";

export function createInitialGameState(): GameState {
  return {
    currentSceneId: "ordinary_morning",
    combat: null,
    player: {
      name: "Unnamed Villager",
      gender: "male",
      realm: "Mortal",
      stage: "Early",
      health: 30,
      maxHealth: 30,
      qi: 0,
      maxQi: 20,
      strength: 1,
      agility: 1,
      endurance: 1,
      intelligence: 1,
      perception: 1,
      spiritualSense: 1,
      physique: 1,
      comprehension: 1,
      willpower: 1,
      karma: 0,
      foundationStability: 100,
      trainingFatigue: 0,
      impurity: 0,
      cultivationInsight: 0,
      daysRemainingToExam: 10,
      spiritStones: 0,
      inventory: [],
      equipment: {},
      techniques: [],
      skills: {},
      skillPractice: {},
      elementalEssence: {},
      constitutions: [],
      techniqueMastery: {},
      quests: {},
      npcJournal: {},
      relationships: {},
      reputation: {},
      morality: {},
      sectContribution: {},
      corruption: 0,
      flags: {},
    },
  };
}
